language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh
  - sudo apt-get install autoconf automake libtool curl make g++ unzip -y
  - sudo apt-get install libprotobuf-dev libprotobuf8 libprotoc8 protobuf-compiler python-protobuf -y
#  - wget https://github.com/google/protobuf/archive/master.zip -O protobuf.zip
#  - unzip protobuf.zip
#  - cd protobuf-master
#  - ./autogen.sh
#  - ./configure --prefix=/usr
#  - make
#  - make check
#  - sudo make install
#  - sudo ldconfig # refresh shared library cache.

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && ./bin/simple_chat_test
